"""C code generator: one loop nest per node, built with gcc, loaded via ctypes.

Deliberately naive.  Every graph node gets its own buffer and its own loop
nest, and index math is spelled out with row-major strides, so the generated
source reads like the IR.

A ``fusion`` node becomes a single loop nest over its output shape.  Its body
is emitted as scalar statements (``float v3 = v1 + v2;``) inside the innermost
loop, and a ``matmul`` inside the body becomes a ``k`` reduction loop feeding
an accumulator, so the epilogue is applied straight to ``acc``.

A ``matmul`` with ``attrs["tile"] = (BM, BN, BK)`` is instead emitted as a
blocked ``ii, jj, kk`` loop nest with an ``i, k, j`` inner order (contiguous
access on both ``w`` and the accumulator) and a ``BM x BN`` accumulator block.
Inside a fusion the epilogue then runs once per block, after its ``k``
reduction finishes, rather than once per element.
"""

from __future__ import annotations

import contextlib
import ctypes
import hashlib
import subprocess
from pathlib import Path

import numpy as np

from .ir import Graph, Node

DEFAULT_BUILD_DIR = Path(__file__).parent / "_build"
DEFAULT_CFLAGS = ("-O3", "-march=native")


# -- emission ---------------------------------------------------------------


def emit_c(graph: Graph) -> str:
    """Return C source for ``void toy_run(const float* <inputs>..., float* out0, ...)``."""
    buf = {}  # Node -> C expression naming its buffer
    for n in graph.inputs:
        buf[n] = n.name
    for i, n in enumerate(graph.outputs):
        buf[n] = f"out{i}"

    params = [f"const float* {n.name}" for n in graph.inputs]
    params += [f"float* out{i}" for i in range(len(graph.outputs))]

    lines = [
        "// generated by toy/codegen_c.py",
        "#define MIN(a, b) ((a) < (b) ? (a) : (b))",
        f"void toy_run({', '.join(params)}) {{",
    ]
    for n in graph.nodes:
        if n not in buf:  # intermediate: give it a static scratch buffer
            buf[n] = "t" + n.name[1:]
            lines.append(f"    static float {buf[n]}[{n.size}];")
    for n in graph.nodes:
        lines.append("")
        lines.append(f"    // {n!r} = {n.op} {' '.join(i.name for i in n.inputs)}")
        lines.extend("    " + l for l in _emit_node(n, buf))
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_node(n: Node, buf: dict[Node, str]) -> list[str]:
    out = buf[n]
    srcs = [buf[i] for i in n.inputs]
    match n.op:
        case "matmul":
            (M, K), (_, N) = n.inputs[0].shape, n.inputs[1].shape
            a, b = srcs
            if n.attrs.get("tile"):
                return _emit_tiled_matmul(
                    n,
                    load_a=lambda i, k, g: f"{a}[{i} * {K} + {k}]",
                    load_b=lambda k, j, g: f"{b}[{k} * {N} + {j}]",
                    epilogue=lambda i, j, acc, g: [f"{out}[{i} * {N} + {j}] = {acc};"],
                )
            return [
                f"for (int i = 0; i < {M}; i++)",
                f"  for (int j = 0; j < {N}; j++) {{",
                "    float acc = 0.0f;",
                f"    for (int k = 0; k < {K}; k++)",
                f"      acc += {a}[i * {K} + k] * {b}[k * {N} + j];",
                f"    {out}[i * {N} + j] = acc;",
                "  }",
            ]
        case "add":
            a, b = srcs
            return [
                f"for (int i = 0; i < {n.size}; i++)",
                f"  {out}[i] = {a}[i] + {b}[i];",
            ]
        case "relu":
            (a,) = srcs
            return [
                f"for (int i = 0; i < {n.size}; i++)",
                f"  {out}[i] = {a}[i] > 0.0f ? {a}[i] : 0.0f;",
            ]
        case "broadcast_in_dim":
            (a,) = srcs
            src = n.inputs[0]
            dims = n.attrs["dims"]
            idx = [f"i{d}" for d in range(len(n.shape))]
            # Target offset uses all dims; source offset uses only the mapped ones.
            dst_off = _offset(idx, n.strides)
            src_off = _offset([idx[d] for d in dims], src.strides)
            lines = []
            for d, size in enumerate(n.shape):
                lines.append("  " * d + f"for (int i{d} = 0; i{d} < {size}; i{d}++)")
            lines.append("  " * len(n.shape) + f"{out}[{dst_off}] = {a}[{src_off}];")
            return lines
        case "fusion":
            return _emit_fusion(n, buf)
        case _:
            raise NotImplementedError(n.op)


def _emit_fusion(n: Node, buf: dict[Node, str]) -> list[str]:
    out, srcs = buf[n], [buf[i] for i in n.inputs]
    nd = len(n.shape)
    idx = tuple(f"i{d}" for d in range(nd))

    tiled = [m for m in n.attrs["body"] if m.op == "matmul" and m.attrs.get("tile")]
    if len(tiled) == 1 and tiled[0].shape == n.shape:
        mm = tiled[0]

        def epilogue(i, j, acc, g):
            # Seed the memo so the epilogue reads the finished block accumulator.
            g.memo[(id(mm), (i, j))] = acc
            value = g.expr(n.attrs["root"], (i, j))
            return [f"{out}[{i} * {n.shape[1]} + {j}] = {value};"]

        return _emit_tiled_matmul(
            mm,
            load_a=lambda i, k, g: g.expr(mm.inputs[0], (i, k)),
            load_b=lambda k, j, g: g.expr(mm.inputs[1], (k, j)),
            epilogue=epilogue,
            gen=_ScalarGen(srcs),
        )

    lines = [
        "  " * d + f"for (int i{d} = 0; i{d} < {size}; i{d}++) {{"
        for d, size in enumerate(n.shape)
    ]
    gen = _ScalarGen(srcs)
    value = gen.expr(n.attrs["root"], idx)
    pad = "  " * nd
    lines += [pad + s for s in gen.stmts]
    lines.append(pad + f"{out}[{_offset(list(idx), n.strides)}] = {value};")
    lines += ["  " * d + "}" for d in reversed(range(nd))]
    return lines


def _emit_tiled_matmul(mm: Node, load_a, load_b, epilogue, gen=None) -> list[str]:
    """Blocked matmul.  ``load_a(i, k, gen)``/``load_b(k, j, gen)`` return C
    expressions (possibly emitting statements into ``gen``); ``epilogue(i, j,
    acc_expr, gen)`` returns the statements that consume one finished element."""
    (M, K), (_, N) = mm.inputs[0].shape, mm.inputs[1].shape
    BM, BN, BK = mm.attrs["tile"]
    gen = gen or _ScalarGen([])
    L = []
    L.append(f"// tiled matmul: tile=({BM}, {BN}, {BK}), inner order i,k,j")
    L.append(f"for (int ii = 0; ii < {M}; ii += {BM}) {{")
    L.append(f"  for (int jj = 0; jj < {N}; jj += {BN}) {{")
    L.append(f"    int iend = MIN(ii + {BM}, {M}), jend = MIN(jj + {BN}, {N});")
    L.append(f"    static float acc[{BM} * {BN}];")
    L.append(f"    for (int t = 0; t < {BM} * {BN}; t++) acc[t] = 0.0f;")
    L.append(f"    for (int kk = 0; kk < {K}; kk += {BK}) {{")
    L.append(f"      int kend = MIN(kk + {BK}, {K});")
    L.append("      for (int i = ii; i < iend; i++)")
    L.append("        for (int k = kk; k < kend; k++) {")
    with gen.scope() as st:
        a = load_a("i", "k", gen)
    L += ["          " + x for x in st]
    L.append(f"          float a = {a};")
    L.append("          for (int j = jj; j < jend; j++) {")
    with gen.scope() as st:
        b = load_b("k", "j", gen)
    L += ["            " + x for x in st]
    L.append(f"            acc[(i - ii) * {BN} + (j - jj)] += a * {b};")
    L.append("          }")
    L.append("        }")
    L.append("    }")
    L.append("    for (int i0 = ii; i0 < iend; i0++)")
    L.append("      for (int i1 = jj; i1 < jend; i1++) {")
    with gen.scope() as st:
        tail = epilogue("i0", "i1", f"acc[(i0 - ii) * {BN} + (i1 - jj)]", gen)
    L += ["        " + x for x in st + tail]
    L.append("      }")
    L.append("  }")
    L.append("}")
    return L


class _ScalarGen:
    """Turn a fusion body into scalar C statements for one output element.

    ``expr(node, idx)`` returns a C expression for ``node`` at the element
    addressed by loop variables ``idx``, appending any statements it needs to
    ``self.stmts``.  Results are memoized per (node, idx) so a value reused by
    two consumers is computed once.
    """

    def __init__(self, srcs: list[str]):
        self.srcs = srcs
        self.stmts: list[str] = []
        self.memo: dict[tuple[int, tuple[str, ...]], str] = {}
        self.counter = 0

    @contextlib.contextmanager
    def scope(self):
        """Collect statements into a fresh list; forget values memoized inside."""
        outer_stmts, outer_keys = self.stmts, set(self.memo)
        self.stmts = []
        try:
            yield self.stmts
        finally:
            self.stmts = outer_stmts
            for k in set(self.memo) - outer_keys:
                del self.memo[k]

    def fresh(self, prefix: str = "v") -> str:
        self.counter += 1
        return f"{prefix}{self.counter - 1}"

    def expr(self, node: Node, idx: tuple[str, ...]) -> str:
        key = (id(node), idx)
        if key in self.memo:
            return self.memo[key]
        match node.op:
            case "param":
                src = self.srcs[node.attrs["index"]]
                v = self.fresh()
                self.stmts.append(f"float {v} = {src}[{_offset(list(idx), node.strides)}];")
            case "broadcast_in_dim":
                # Pure index remap: the source element is idx restricted to mapped dims.
                v = self.expr(node.inputs[0], tuple(idx[d] for d in node.attrs["dims"]))
            case "add":
                a = self.expr(node.inputs[0], idx)
                b = self.expr(node.inputs[1], idx)
                v = self.fresh()
                self.stmts.append(f"float {v} = {a} + {b};")
            case "relu":
                a = self.expr(node.inputs[0], idx)
                v = self.fresh()
                self.stmts.append(f"float {v} = {a} > 0.0f ? {a} : 0.0f;")
            case "matmul":
                i, j = idx
                K = node.inputs[0].shape[1]
                acc, k = self.fresh("acc"), self.fresh("k")
                self.stmts.append(f"float {acc} = 0.0f;")
                self.stmts.append(f"for (int {k} = 0; {k} < {K}; {k}++) {{")
                with self.scope() as inner:
                    a = self.expr(node.inputs[0], (i, k))
                    b = self.expr(node.inputs[1], (k, j))
                    inner.append(f"{acc} += {a} * {b};")
                self.stmts += ["  " + s for s in inner]
                self.stmts.append("}")
                v = acc
            case _:
                raise NotImplementedError(node.op)
        self.memo[key] = v
        return v


def _offset(idx: list[str], strides: tuple[int, ...]) -> str:
    terms = [f"{i} * {s}" if s != 1 else i for i, s in zip(idx, strides)]
    return " + ".join(terms) if terms else "0"


# -- build + load -----------------------------------------------------------


class Compiled:
    def __init__(self, graph: Graph, source: str, lib_path: Path):
        self.graph = graph
        self.source = source
        self.lib_path = lib_path
        self._lib = ctypes.CDLL(str(lib_path))
        self._fn = self._lib.toy_run
        nargs = len(graph.inputs) + len(graph.outputs)
        self._fn.argtypes = [ctypes.POINTER(ctypes.c_float)] * nargs
        self._fn.restype = None

    def __call__(self, *args: np.ndarray) -> list[np.ndarray]:
        if len(args) != len(self.graph.inputs):
            raise ValueError(f"expected {len(self.graph.inputs)} inputs, got {len(args)}")
        ins = []
        for node, arr in zip(self.graph.inputs, args):
            arr = np.ascontiguousarray(arr, dtype=np.float32)
            if arr.shape != node.shape:
                raise ValueError(f"input {node!r} got array of shape {arr.shape}")
            ins.append(arr)
        outs = [np.empty(o.shape, dtype=np.float32) for o in self.graph.outputs]
        ptr = ctypes.POINTER(ctypes.c_float)
        self._fn(*(a.ctypes.data_as(ptr) for a in ins + outs))
        return outs


def compile_graph(
    graph: Graph,
    build_dir: Path | str | None = None,
    cflags: tuple[str, ...] = DEFAULT_CFLAGS,
) -> Compiled:
    build_dir = Path(build_dir) if build_dir else DEFAULT_BUILD_DIR
    build_dir.mkdir(parents=True, exist_ok=True)
    source = emit_c(graph)
    tag = hashlib.sha1((source + " ".join(cflags)).encode()).hexdigest()[:10]
    c_path = build_dir / f"toy_{tag}.c"
    so_path = build_dir / f"toy_{tag}.so"
    if not so_path.exists():
        c_path.write_text(source)
        subprocess.run(
            ["gcc", *cflags, "-shared", "-fPIC", "-o", str(so_path), str(c_path)],
            check=True,
        )
    return Compiled(graph, source, so_path)
