"""C code generator: one loop nest per node, built with gcc, loaded via ctypes.

Deliberately naive.  Every intermediate gets its own buffer and its own loop
nest, and index math is spelled out with row-major strides, so the generated
source reads like the IR.  Fusion and tiling are later exercises.
"""

from __future__ import annotations

import ctypes
import hashlib
import subprocess
from pathlib import Path

import numpy as np

from .ir import Graph, Node

DEFAULT_BUILD_DIR = Path(__file__).parent / "_build"


# -- emission ---------------------------------------------------------------


def emit_c(graph: Graph) -> str:
    """Return C source for ``void toy_run(const float* <inputs>..., float* out0, ...)``."""
    buf = {}  # Node -> C expression naming its buffer
    for n in graph.inputs:
        buf[n] = n.name
    for i, n in enumerate(graph.outputs):
        buf[n] = f"out{i}"

    params = [f"const float* {n.name}" for n in graph.inputs]
    params += [f"float* out{i}" for i in range(len(graph.outputs))]

    lines = [
        "// generated by toy/codegen_c.py",
        f"void toy_run({', '.join(params)}) {{",
    ]
    for n in graph.nodes:
        if n not in buf:  # intermediate: give it a static scratch buffer
            buf[n] = "t" + n.name[1:]
            lines.append(f"    static float {buf[n]}[{n.size}];")
    for n in graph.nodes:
        lines.append("")
        lines.append(f"    // {n!r} = {n.op} {' '.join(i.name for i in n.inputs)}")
        lines.extend("    " + l for l in _emit_node(n, buf))
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_node(n: Node, buf: dict[Node, str]) -> list[str]:
    out = buf[n]
    srcs = [buf[i] for i in n.inputs]
    match n.op:
        case "matmul":
            (M, K), (_, N) = n.inputs[0].shape, n.inputs[1].shape
            a, b = srcs
            return [
                f"for (int i = 0; i < {M}; i++)",
                f"  for (int j = 0; j < {N}; j++) {{",
                "    float acc = 0.0f;",
                f"    for (int k = 0; k < {K}; k++)",
                f"      acc += {a}[i * {K} + k] * {b}[k * {N} + j];",
                f"    {out}[i * {N} + j] = acc;",
                "  }",
            ]
        case "add":
            a, b = srcs
            return [
                f"for (int i = 0; i < {n.size}; i++)",
                f"  {out}[i] = {a}[i] + {b}[i];",
            ]
        case "relu":
            (a,) = srcs
            return [
                f"for (int i = 0; i < {n.size}; i++)",
                f"  {out}[i] = {a}[i] > 0.0f ? {a}[i] : 0.0f;",
            ]
        case "broadcast_in_dim":
            (a,) = srcs
            src = n.inputs[0]
            dims = n.attrs["dims"]
            idx = [f"i{d}" for d in range(len(n.shape))]
            # Target offset uses all dims; source offset uses only the mapped ones.
            dst_off = _offset(idx, n.strides)
            src_off = _offset([idx[d] for d in dims], src.strides)
            lines = []
            for d, size in enumerate(n.shape):
                lines.append("  " * d + f"for (int i{d} = 0; i{d} < {size}; i{d}++)")
            lines.append("  " * len(n.shape) + f"{out}[{dst_off}] = {a}[{src_off}];")
            return lines
        case _:
            raise NotImplementedError(n.op)


def _offset(idx: list[str], strides: tuple[int, ...]) -> str:
    terms = [f"{i} * {s}" if s != 1 else i for i, s in zip(idx, strides)]
    return " + ".join(terms) if terms else "0"


# -- build + load -----------------------------------------------------------


class Compiled:
    def __init__(self, graph: Graph, source: str, lib_path: Path):
        self.graph = graph
        self.source = source
        self.lib_path = lib_path
        self._lib = ctypes.CDLL(str(lib_path))
        self._fn = self._lib.toy_run
        nargs = len(graph.inputs) + len(graph.outputs)
        self._fn.argtypes = [ctypes.POINTER(ctypes.c_float)] * nargs
        self._fn.restype = None

    def __call__(self, *args: np.ndarray) -> list[np.ndarray]:
        if len(args) != len(self.graph.inputs):
            raise ValueError(f"expected {len(self.graph.inputs)} inputs, got {len(args)}")
        ins = []
        for node, arr in zip(self.graph.inputs, args):
            arr = np.ascontiguousarray(arr, dtype=np.float32)
            if arr.shape != node.shape:
                raise ValueError(f"input {node!r} got array of shape {arr.shape}")
            ins.append(arr)
        outs = [np.empty(o.shape, dtype=np.float32) for o in self.graph.outputs]
        ptr = ctypes.POINTER(ctypes.c_float)
        self._fn(*(a.ctypes.data_as(ptr) for a in ins + outs))
        return outs


def compile_graph(graph: Graph, build_dir: Path | str | None = None) -> Compiled:
    build_dir = Path(build_dir) if build_dir else DEFAULT_BUILD_DIR
    build_dir.mkdir(parents=True, exist_ok=True)
    source = emit_c(graph)
    tag = hashlib.sha1(source.encode()).hexdigest()[:10]
    c_path = build_dir / f"toy_{tag}.c"
    so_path = build_dir / f"toy_{tag}.so"
    if not so_path.exists():
        c_path.write_text(source)
        subprocess.run(
            ["gcc", "-O2", "-shared", "-fPIC", "-o", str(so_path), str(c_path)],
            check=True,
        )
    return Compiled(graph, source, so_path)
